feat/listPendindCollaborations
Grupo-GCB/academy-gamification pull request #14
Opened 2023-02-24 20:29 UTC by VitorMantovani

Neste PR foi implementado a feature de listagem das colaboraçoes pendentes.

Alterações feitas:

Academys:

- Implementação da entidade academys
- Criação do IAcademyRepository com os  métodos create e findById
- Implementacão dos métods create e findById no repositório in-memory
- Criação do use-case find-academy-by-id, junto de seu teste unitário
- Implementação do método findById no repositório TypeOrm
- Criação do controller e implementando o método findById (GET)

Collaboratios:
- Implementação da entidade collaborations
- Criação do ICollaborationsRepository com os métodos create e  filterCollaborationsByStatus
- Implementacão dos método create e filterCollaborationsByStatus no repositório in-memory
- Criação do use-case filter-collaborations-by-status, junto de seu teste unitário
- Implementação do método filterByStatus no repositório TypeOrm
- Criação do controller e implementando o método filterByStatus (GET)

2023-02-24 22:48 UTC, RafaRamosCosta requested changes

2023-02-24 22:48 UTC, RafaRamosCosta commented on server/src/collaborations/infra/typeorm/entities/collaboration.entity.ts
> +export enum CollaborationsStatus {
Mover esse enum uma pasta constants

2023-02-24 22:48 UTC, RafaRamosCosta commented on server/src/collaborations/infra/typeorm/repositories/collaborations.repository.ts
> +    const academyCollaborations = await this.collaborationsRepository.find({
Essa lógica está errada, desse jeito você vai listar apenas uma colaboração.

Teria que ser where: {academy_id} por exemplo.

2023-02-24 22:48 UTC, RafaRamosCosta commented on server/src/collaborations/interfaces/ICollaborationsRepository.ts
> +    id,
Ao invés de usar id, que dá a entender que é o id da collaboration, usar academy_id.

2023-02-24 22:48 UTC, RafaRamosCosta commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filter-collaborations-by-status.ts
> +        id,
Aqui seria o id do academy tbm, então coloca academy_id

2023-02-24 22:48 UTC, RafaRamosCosta commented on server/src/shared/infra/http/controllers/collaborations.controller.ts
> +    { status, id }: FilterCollaborationByStatusDto,
trocar id por academy_id

2023-02-25 00:50 UTC, LeonardoRCosta commented on server/src/academys/use-cases/findById/find-academy-by-id.spec.ts
> +    const academyFinded = await findByIdUseCase.execute(academy.id);
Acredito que não mudaria muito, mas se avaliado pelo padrão do manguinho, como estamos testando para ver se o academy foi criado, ou seja, se após a execução do método create ele possui um id, seria válido mudar o nome de academyFinded para sut (System Under Test).
Acho válido alinhar com todos para seguir o mesmo padrão!

2023-02-25 01:00 UTC, VitorMantovani commented on server/src/academys/use-cases/findById/find-academy-by-id.spec.ts
> +    const academyFinded = await findByIdUseCase.execute(academy.id);
Alterado!

2023-02-25 02:25 UTC, LeonardoRCosta requested changes

2023-02-25 02:25 UTC, LeonardoRCosta commented on server/src/collaborations/interfaces/ICollaborationsRepository.ts
> +  abstract filterCollaborationsByStatus({
Se esse método for específicamente para colaborações que envolvem o academy, escopar melhor o método e a lógica para trazer apenas as do academy, ou se for pra deixar para todas as colaborações não utilizar ids

2023-02-25 02:25 UTC, LeonardoRCosta commented on server/src/collaborations/test/in-memory/inMemoryCollaborationsRepository.ts
> +import { CreateCollaborationDto } from './../../dto/create-collaboration.dto';
utilizar o @ no path

2023-02-25 02:25 UTC, LeonardoRCosta commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filter-collaborations-by-status.ts
> +    if (pendingCollaborations.length === 0) {
Tirar as chaves

`if (pendingCollaborations.length === 0) throw new NotFoundException('No collaborations were found')`

2023-02-25 02:25 UTC, LeonardoRCosta commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filterCollaborationsByStatus.spec.ts
> +import { InMemoryCollaborationsRepository } from '@collaborations/test/in-memory/inMemoryCollaborationsRepository';
Organizar imports de acordo com o padrão

2023-02-25 02:25 UTC, LeonardoRCosta commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filterCollaborationsByStatus.spec.ts
> +        id: 'Invalid',
Nesse teste busque passar um id válido, pois parece que você está passando um usuário inválido e por isso do erro.

Acredito que esse teste vai mudar já que o método irá mudar também

2023-02-25 02:25 UTC, LeonardoRCosta commented on server/src/shared/infra/http/controllers/academys.controllers.ts
> +import { Controller, Get, Param } from '@nestjs/common';
Organizar imports e usar o @

2023-02-25 02:25 UTC, LeonardoRCosta commented on server/src/shared/infra/http/controllers/academys.controllers.ts
> +  @Get('academys/:id')
Quando vc coloca 'academys' no decorator do controller você está colocando um prefixo, se você começar a rota get com academys/:id essa rota ficaria assim:

http://localhost:3333/academys/academys/:id

Então pode retirar o academys do @Get() e deixar somente o :id

2023-02-25 02:25 UTC, LeonardoRCosta commented on server/src/shared/infra/http/controllers/collaborations.controller.ts
> +  @Get('collaborations/academy/:id')
Mesma coisa do Academys controller, pode retirar o collaborations do @Get()

2023-02-25 19:21 UTC, Kayke-Fujinaka requested changes

2023-02-25 19:21 UTC, Kayke-Fujinaka commented on server/src/collaborations/test/in-memory/inMemoryCollaborationsRepository.ts
> +  async filterCollaborationsByStatus({
Refatora isso!!

Não tem sentido fazer 2 filter, sendo que poderia fazer tudo em um único filter.

Exemplo:
```
const collaborations = [
  {
    academy_id: 1,
    status: "aprove",
  },
  {
    academy_id: 2,
    status: "pending",
  },
  {
    academy_id: 3,
    status: "reject",
  },
  {
    academy_id: 2,
    status: "pending",
  },
];

function filterCollaborationsByStatusAndAcademyId({ academy_id, status }) {
  const filteredCollaborations = collaborations.filter(
    (collaboration) =>
      collaboration.status === status && collaboration.academy_id === academy_id
  );

  return filteredCollaborations;
}

console.log(
  filterCollaborationsByStatusAndAcademyId({ academy_id: 2, status: "pending" })
);

```

2023-02-25 19:21 UTC, Kayke-Fujinaka commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filter-collaborations-by-status.ts
> +    if (pendingCollaborations.length === 0)
Utilizar o operador opcional "?." para checar se o array pendingCollaborations é nulo ou indefinido antes de verificar seu tamanho com length.

Exemplo:
```
   if (!pendingCollaborations?.length)
```

2023-02-25 19:21 UTC, Kayke-Fujinaka commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filter-collaborations-by-status.ts
> +export class FilterCollaborationsByStatus {
Exportar a pasta filterCollaborationsByStatus com um Barrel Exports

2023-02-25 19:21 UTC, Kayke-Fujinaka commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filter-collaborations-by-status.ts
> +export class FilterCollaborationsByStatus {
Mudar esse nome deixando algo mais legível e de acordo com o que ele faz.

Ele filtra pelo status e academy_id

2023-02-25 19:21 UTC, Kayke-Fujinaka commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filter-collaborations-by-status.ts
> +  async execute({
Criar uma validação de entrada para validar se na hora da requisição o `academy_id` e o `status` estão preenchidos ou vazios.

2023-02-25 19:21 UTC, Kayke-Fujinaka commented on server/src/academys/use-cases/findById/find-academy-by-id.ts
> +    if (!academy) throw new NotFoundException('Academy does not exist');
Deixa a mensagem de erro mais informativa com um template literal informando o id do Academy e falando que esse id não existe.

2023-02-25 19:21 UTC, Kayke-Fujinaka commented on server/src/collaborations/test/in-memory/inMemoryCollaborationsRepository.ts
> +  async filterCollaborationsByStatus({
Lembrando que as algumas colaborações terão mais de um Academy envolvido, então mudar essa lógica ai.

2023-02-25 19:21 UTC, Kayke-Fujinaka commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filterCollaborationsByStatus.spec.ts
> +import { CollaborationsStatus } from 'shared/constants';
Utilizar o Path Mapping do `shared`

2023-02-25 19:21 UTC, Kayke-Fujinaka commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filterCollaborationsByStatus.spec.ts
> +    const collaboration1 = await inMemoryCollaborationRepository.create({
Coloca um id diferente para cada coisa.

Você copiou e ficou colando o mesmo id.

Deixa um negócio feito com mais carinho e pensando em um cenário real.

2023-02-25 19:21 UTC, Kayke-Fujinaka commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filterCollaborationsByStatus.spec.ts
> +    const collaboration1 = await inMemoryCollaborationRepository.create({
Isso vale para todos os que você criou abaixo, também.

2023-02-25 19:21 UTC, Kayke-Fujinaka commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filterCollaborationsByStatus.spec.ts
> +  it('should find academy with passed collaboration status passed', async () => {
"should find academies with the collaboration status passed"

2023-02-25 19:21 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/academys.controllers.ts
> +export class AcademysController {
Faltou o Swagger

Deve conter os casos de sucesso e erros com exemplos.

2023-02-25 19:21 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/collaborations.controller.ts
> +export class CollaborationsController {
Faltou o Swagger

Deve conter os casos de sucesso e erros com exemplos.

2023-02-25 21:33 UTC, VitorMantovani commented on server/src/academys/infra/typeorm/entities/academy.entity.ts
> +export class Academy {
Mas o academy vai poder ter os seus dados alterados!?

2023-02-25 21:50 UTC, Kayke-Fujinaka commented on server/src/academys/infra/typeorm/entities/academy.entity.ts
> +export class Academy {
Real, @VitorMantovani.
Seria melhor estressar um pouco mais sobre isso, mas creio que não tenha como manipular de alguma forma os dados do OAuth.

Deixa apenas o deleted caso precise remover um Academy que foi desligado ou subir para um time principal.

2023-02-25 21:59 UTC, Kayke-Fujinaka commented
@VitorMantovani faltou fazer a parte do Front-End, tbm

2023-02-25 23:45 UTC, LeonardoRCosta commented on server/src/collaborations/infra/typeorm/entities/collaboration.entity.ts
> +  @ManyToMany(() => Academy)
Analisando o MER, a relação é realmente many to many, pois um academy pode estar em várias colaborações e uma colaboração poder ter vários academys, porém não pode ser uma string, deve ser um array de strings, ou seja, um array de academyId.

2023-02-25 23:52 UTC, RafaRamosCosta commented on server/src/collaborations/infra/typeorm/entities/collaboration.entity.ts
> +  @ManyToMany(() => Academy)
Apesar de achar mais fácil utilizar um array de ids de academy, acredito que nesse caso poderia ser tanto um array de Academys quanto um array de ids de academys, ou seja, um array de string. 

Mas de qualquer forma tem que ser um array, pra poder receber mais de um "academy" por colaboração.

2023-02-26 00:34 UTC, VitorMantovani commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filter-collaborations-by-status.ts
> +export class FilterCollaborationsByStatus {
Corrigido!

2023-02-26 00:39 UTC, VitorMantovani commented on server/src/collaborations/use-cases/filterCollaborationsByStatus/filter-collaborations-by-status.ts
> +    if (pendingCollaborations.length === 0)
Corrigido!

2023-02-26 00:43 UTC, VitorMantovani commented on server/src/collaborations/test/in-memory/inMemoryCollaborationsRepository.ts
> +  async filterCollaborationsByStatus({
Lógica refatorada!

2023-02-26 00:46 UTC, VitorMantovani commented on server/src/collaborations/infra/typeorm/entities/collaboration.entity.ts
> +  @ManyToMany(() => Academy)
Eu me atentei somente a tipagem do Id, que vai ter uma string, mas ja alterei a propriedade para um array!

2023-02-26 00:46 UTC, VitorMantovani commented on server/src/collaborations/infra/typeorm/entities/collaboration.entity.ts
> +import { CollaborationsStatus } from 'shared/constants';
Corrigido!

2023-02-26 00:55 UTC, VitorMantovani commented on server/src/collaborations/dto/filter-collaboration-by-status.dto.ts
> +export class FilterCollaborationByStatusDto {
Nome alterado!

2023-02-26 00:55 UTC, VitorMantovani commented on server/src/collaborations/dto/create-collaboration.dto.ts
> +export class CreateCollaborationDto {
Corrigido!

2023-02-26 00:56 UTC, VitorMantovani commented on server/src/collaborations/dto/filter-collaboration-by-status.dto.ts
> +import { CollaborationsStatus } from 'shared/constants';
Adicionei o path mapping!

2023-02-26 01:07 UTC, VitorMantovani commented on server/src/academys/use-cases/findById/find-academy-by-id.spec.ts
> +      email: 'academy@academy.com',
Alterado!

2023-02-26 01:08 UTC, VitorMantovani commented on server/src/academys/academys.module.ts
> +import { FindByIdUseCase } from './use-cases/findById/find-academy-by-id';
index.ts para as exportações criado!

2023-02-26 01:08 UTC, VitorMantovani commented on server/src/academys/infra/typeorm/entities/academy.entity.ts
> +export class Academy {
adicionei o deleted_at

2023-02-26 15:16 UTC, Kayke-Fujinaka requested changes

2023-02-26 15:16 UTC, Kayke-Fujinaka commented on server/src/collaborations/dto/create-collaboration.dto.ts
> +  academy_id: string[];
Faltou aplicar os decorators corretos!

```
  @IsNotEmpty()
  @IsArray()
  @IsString({ each: true })
  academy_id: string[];
```

2023-02-26 15:16 UTC, Kayke-Fujinaka commented on server/src/collaborations/infra/typeorm/repositories/collaborations.repository.ts
> +    const academyCollaborations = await this.collaborationsRepository.find({
Você poderia colocar o status junto no where:
```

  async filterByAcademyAndStatus(
    status: CollaborationsStatus,
    academy_id: string,
  ): Promise<Collaboration[]> {
    return this.collaborationsRepository.find({
      where: { academy_id, status },
    });
  }
}
```

2023-02-26 15:16 UTC, Kayke-Fujinaka commented on server/src/collaborations/use-cases/filterByAcademyAndStatus/filter-by-academy-and-status.spec.ts
> +        academy_id: 'academy',
Simula um id real.

`186135a-6bad-4124-be11-98h1g7Dse3ca`

2023-02-26 15:16 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/academys.controllers.ts
> +import { FindByIdUseCase } from '../../../../academys/use-cases/findById/find-academy-by-id';
Você resolveu a conversation acima, mas não arrumou o caminho com o Path Mapping do `@academys`.

Além disso, você deve criar um Barrel Exports, ou seja, criar aquele index exportando todas as pastas use-cases.

2023-02-26 15:16 UTC, Kayke-Fujinaka commented on server/src/academys/academys.module.ts
> +import { AcademysController } from './../shared/infra/http/controllers/academys.controllers';
Utilizar o Path Mapping do @shared

2023-02-26 15:16 UTC, Kayke-Fujinaka commented on server/src/academys/infra/typeorm/repositories/academys.repository.ts
> +import { Academy } from '../entities/academy.entity';
Utilizar o Path Mapping do @academys

2023-02-26 15:16 UTC, Kayke-Fujinaka commented on server/src/collaborations/collaborations.module.ts
> +import { CollaborationsRepository } from './infra/typeorm/repositories/collaborations.repository';
`import { CollaborationsRepository } from '@collaborations/infra/typeorm/repositories/collaborations.repository';`

2023-02-26 15:16 UTC, Kayke-Fujinaka commented on server/src/collaborations/infra/typeorm/repositories/collaborations.repository.ts
> +import { Collaboration } from '../entities/collaboration.entity';
Utilizar o Path Mapping do `@collaborations`

2023-02-26 15:16 UTC, Kayke-Fujinaka commented on server/src/collaborations/test/in-memory/inMemoryCollaborationsRepository.ts
> +import { CreateCollaborationDTO } from './../../dto/create-collaboration.dto';
Utilizar o Path Mapping do `@collaborations`

2023-02-26 15:16 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/collaborations.controller.ts
> +import { FilterByAcademyAndStatus } from '@collaborations/use-cases/filterByAcademyAndStatus/filter-by-academy-and-status';
Falta criar o Barrel Export dos use-cases das collaborations

2023-02-26 15:23 UTC, Kayke-Fujinaka requested changes

2023-02-26 15:23 UTC, Kayke-Fujinaka commented on server/src/collaborations/dto/filter-collaboration-by-status.dto.ts
> +export class FilterCollaborationByStatusDto {
Falta alterar isso ainda

2023-02-26 21:52 UTC, VitorMantovani commented on server/src/shared/infra/http/controllers/collaborations.controller.ts
> +  @Get('academy/:id')
Corrigido

2023-02-26 21:59 UTC, VitorMantovani commented on server/src/academys/test/in-memory/InMemoryAcademysRepository.ts
> +  async create(data: CreateAcademyDTO): Promise<Academy> {
Corrigido!

2023-02-26 23:17 UTC, VitorMantovani commented on server/src/shared/constants/index.ts
> +export enum CollaborationsStatus {
Corrigido

2023-02-27 08:40 UTC, Kayke-Fujinaka requested changes

2023-02-27 08:40 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/academys.controllers.ts
>  @Controller('academys')
Dar um enter entre o import e o `@Controller("academys")`

2023-02-27 08:40 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/collaborations.controller.ts
>  import { FilterByAcademyAndStatusDTO } from '@collaborations/dto/filter-by-academy-and-status';
Você já criou um Barrel Export para os DTOs, então não precisa passar o caminho inteiro.

Pode passar o caminho até `/dto/`

2023-02-27 08:40 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/collaborations.controller.ts
>  import { FilterByAcademyAndStatusDTO } from '@collaborations/dto/filter-by-academy-and-status';
Faça isso com todos os outros que você foi passando o caminho inteiro.

É só ir na lupinha do VsCode e pesquisar por `/dto/` que vai aparecer todos os casos. Ai, é só apagar o caminho inteiro e deixar até o `/dto/`.

Exemplo:
`@collaborations/dto/`

2023-02-27 08:49 UTC, Kayke-Fujinaka requested changes

2023-02-27 08:49 UTC, Kayke-Fujinaka commented on server/src/collaborations/use-cases/filterByAcademyAndStatus/filter-by-academy-and-status.spec.ts
> +describe('Find Collaboration by Academy id', () => {
Em um dos test coloca mais de um id no `academy_id` e testa se NÃO foi possível encontrar por esse id.

Utilizar o `.not` do JEST

Ex:
```
    const collaboration2 = await inMemoryCollaborationRepository.create({
      collaboration_type_id: 'e802eade-11c6-4c94-9e0b-37dfdfd67c87',
      collaborator_id: '3ed27bd9-9a87-4f75-9a84-17e1949311d3',
      academy_id: ['bb324053-cfe0-49ad-9c24-1d6bd368555e', '37952c7d-5b92-47f4-befe-340e6ed7d1a5'],
      status: CollaborationsStatus.PENDING,
    });
```

2023-02-27 08:49 UTC, Kayke-Fujinaka commented on server/src/collaborations/use-cases/filterByAcademyAndStatus/filter-by-academy-and-status.ts
> +      throw new BadRequestException('Id and Status are required!');
Dar um enter desse throw new Error com a variável pendingCollaborations

2023-03-02 21:05 UTC, closed without merging