Feat/admin-analyze-pending-collaboration
Grupo-GCB/academy-gamification pull request #16
Opened 2023-03-03 20:54 UTC by VitorMantovani

Neste PR foi implementado a feature de análise de colaborações.

Alterações feitas

Collaboratios:

Criação do ICollaborationsRepository com os métodos findOne e updateStatus
Implementacão dos métodos findOne e updateStatus no repositório in-memory
Criação do use-cases findOne e updateStatus, junto de seus testes unitários
Implementação dos métodos findOne e updateStatus no repositório TypeOrm
Criação do controller e implementando os métodos findOne (GET)  e updateStatus (PUT)

2023-03-03 21:23 UTC, Kayke-Fujinaka requested changes

2023-03-03 21:23 UTC, Kayke-Fujinaka commented on server/src/collaborations/use-cases/updateStatus/update-status.spec.ts
> +} from '@shared/constants/index';
Tirar esse "/index"

2023-03-03 21:23 UTC, Kayke-Fujinaka commented on server/src/collaborations/use-cases/updateStatus/update-status.ts
> +      throw new NotFoundException('Collaboration not found!');
Tira as exclamações do final de todos esses Exception

2023-03-03 21:23 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/collaborations.controller.ts
>  @Controller('collaborations')
Colocar o Swagger nos DTOs

2023-03-03 21:35 UTC, GuWuelta approved these changes

2023-03-07 16:24 UTC, RafaRamosCosta requested changes

2023-03-07 16:41 UTC, Kayke-Fujinaka approved these changes

2023-03-07 18:18 UTC, RafaRamosCosta approved these changes

2023-03-07 18:46 UTC, merged