feat/admin-analyze-pending-transaction
Grupo-GCB/academy-gamification pull request #20
Opened 2023-03-08 20:12 UTC by GuWuelta

# Descrição da tarefa
Neste PR foi implementada a funcionalidade do administrador analisar uma solicitação de transação

# Checklist
Você realizou o code review do seu próprio PR?
- [x] Sim
- [] Não
---
Foi necessária documentação nessa task?
- [] Sim
- [x] Não
---
Necessário seguir alguma ordem de deploy (ex: aceitar outro PR antes)?
- [] Sim
- [x] Não

# Testes realizados
- [x] Unitários
- [x] Integração
- [] QA

2023-03-08 22:06 UTC, Kayke-Fujinaka requested changes

2023-03-08 22:06 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/findById/find-by-id.spec.ts
> +  it('shoud be able to find a transaction by id', async () => {
Criar mais uma colaboração e faça um teste validando se ela NÃO foi encontrada

2023-03-08 22:06 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/updateStatus/update-status.ts
> +    if (!newStatus) throw new BadRequestException('newStatus is required');
Se está validando se o newStatus foi passado, é necessário validar o id da transação também :)

2023-03-08 22:08 UTC, Kayke-Fujinaka requested changes

2023-03-09 13:53 UTC, VitorMantovani approved these changes
PR revisado

2023-03-09 17:06 UTC, Kayke-Fujinaka requested changes

2023-03-09 17:06 UTC, Kayke-Fujinaka commented on server/src/transactions/infra/typeorm/repositories/transactions.repository.ts
> +      where: { id: id },
`where: { id }`, não precisa colocar `id: id`

2023-03-09 17:06 UTC, Kayke-Fujinaka commented on server/src/transactions/infra/typeorm/repositories/transactions.repository.ts
> +    await this.transactionsRepository.update({ id: id }, { status: newStatus });
`where: { id }`, não precisa colocar `id: id`

2023-03-09 17:06 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/findById/find-by-id.spec.ts
> +  it('shoud be able to find just a one transaction by id', async () => {
Você não validou nada aqui!

Precisa testar se a transação 2 NÃO foi encontrada.

Existe um método `not` no jest que consegue realizar testes que não esperem tal comportamento.

Além disso, não precisa criar mais um `it`, você pode criar e testar se não existe no primeiro it que `shoud be able to find a transaction by id`

2023-03-09 17:29 UTC, Kayke-Fujinaka approved these changes

2023-03-09 17:50 UTC, Kayke-Fujinaka approved these changes

2023-03-09 17:50 UTC, merged