Refactor/modules
Grupo-GCB/academy-gamification pull request #21
Opened 2023-03-14 20:30 UTC by GuWuelta

Neste PR foi iniciada a refatoração de todos os módulos presentes na aplicação.

2023-03-14 20:34 UTC, Kayke-Fujinaka requested changes

2023-03-14 20:34 UTC, Kayke-Fujinaka commented on server/src/shared/constants/index.ts
> +  CEREMONY = 'CEREMONY',
TEAMCERIMONY = "TEAM_CERIMONY"

2023-03-15 16:57 UTC, Kayke-Fujinaka requested changes

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/transactions/infra/typeorm/entities/transaction.entity.ts
> -  @Column('text', { array: true })
Pode tirar a coluna Academy

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/users/use-cases/registerUser/register-user.ts
> +  async execute(data: RegisterUserDTO): Promise<User> {
Precisa validar se já existe um email criado (Pode deixar para a próxima task de criar um usuário)

Desestruturar essa "data" do caso de uso

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/users/use-cases/registerUser/register-user.ts
> +import { RegisterUserDTO } from '@users/dto/register-user-dto';
Usar o barrel export do DTO

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/users/use-cases/findByEmail/find-by-email.spec.ts
> +      await sut.execute('kayke.wuelta@gcbinvestimentos.com');
Coloca john.doe ou algum outro nome que deixa descritivo que não existe

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/users/use-cases/findByEmail/find-by-email.spec.ts
> +describe('Find an user by id', () => {
A descrição está errada

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/users/use-cases/registerUser/register-user.spec.ts
> +describe('Register collaborator', () => {
Descrição está errada

"Register User", além disso deve ser possível registrar os 3 tipos de Roles cada um em um "it"

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/users/test/in-memory/inMemoryUserRepository.ts
> +import { RegisterUserDTO } from '@users/dto/register-user-dto';
Usar o Barrel export

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/updateStatus/update-status.ts
> +      throw new Error('you must be a administrator');
Arruma essa mensagem de erro e coloca o exception de não estar autorizado

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/updateStatus/update-status.ts
> +    if ((await responsible).role != Roles.ADMIN) {
Tirar o await

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/updateStatus/update-status.ts
> +    if (!new_status) throw new BadRequestException('new_status is required');
Arruma essa mensagem de erro! Não tem sentido colocar underline

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/updateStatus/update-status.ts
>      if (!id) throw new BadRequestException('id is required');
Deixa maiúsculo o "Id"

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/updateStatus/update-status.spec.ts
> +
should not be able to update a "transaction" if user is not a administrator

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/registerTransaction/register-transaction.ts
> +    const responsible = await this.usersRepository.findOne(data.responsible);
Desestrutura esse responsible

2023-03-15 16:57 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/registerTransaction/register-transaction.ts
> +    if (
Junta esses IFs em um, pois eles retornam o mesmo erro.

if (
  (responsible.role === Roles.COLLABORATOR && data.reason !== Reasons.REDEEM) ||
  (responsible.role === Roles.ACADEMY && data.reason !== Reasons.COLLABORATION)
) {
  throw new UnauthorizedException('You do not have permission');
}

Além disso, melhora essa validação gigantesca deixando enxuta e tacando um includes

2023-03-15 19:36 UTC, GuWuelta commented on server/src/transactions/use-cases/updateStatus/update-status.ts
> +    if ((await responsible).role != Roles.ADMIN) {
O await nesse caso é necessário

2023-03-15 20:00 UTC, GuWuelta commented on server/src/shared/infra/http/controllers/transactions.e2e.spec.ts
> +      collaborator: 'levi.ciarrochi@gcbinvestimentos.com',
Nesse caso não pq estamos mockando o teste e os resultados

2023-03-15 23:44 UTC, Kayke-Fujinaka approved these changes

2023-03-15 23:44 UTC, merged