Feat/user-authenticationFeature
Grupo-GCB/academy-gamification pull request #30
Opened 2023-03-23 17:00 UTC by VitorMantovani

Neste PR foi implementado a feature de autenticação

2023-03-23 17:32 UTC, GuWuelta requested changes

2023-03-23 17:32 UTC, GuWuelta commented on server/src/auth/auth.service.ts
> +    // if (user) {
Apagar os comentários

2023-03-23 17:32 UTC, GuWuelta commented on server/src/auth/auth.service.ts
> +    console.log(refreshToken);
Apagar console.log()

2023-03-23 17:32 UTC, GuWuelta commented on server/src/auth/dto/refresh-token.dto.ts
> +  @IsEmail()
Alterar decorator

2023-03-23 17:32 UTC, GuWuelta commented on server/src/auth/guards/refresh-token.guard.ts
> +import { AuthService } from '@auth/auth.service';
Pular linha p/ separação dos imports

2023-03-23 17:32 UTC, GuWuelta commented on server/src/main.ts
> +    .addTag('auth')
Confirmou no Swagger se tá funcionando certo essa Tag? Estamos fazendo sem utilizar tags porque tava tudo indo pro Default e as tags estavam ficando vazias dentro do Swagger

2023-03-23 17:32 UTC, GuWuelta commented on server/src/shared/infra/http/controllers/auth.controller.ts
> +@Controller()
Coloca 'auth' dentro do Controller

2023-03-23 17:32 UTC, GuWuelta commented on server/src/users/test/in-memory/inMemoryUserRepository.ts
> +  async findOne(id: string): Promise<User> {
findOne foi alterado pra findById na task do Kayke, provavelmente terá que ser resolvido nos conflitos

2023-03-23 17:32 UTC, GuWuelta commented on server/src/users/use-cases/findById/findById.spec.ts
> +describe('Find an user by email', () => {
Find an user by id*

2023-03-24 17:27 UTC, RafaRamosCosta requested changes

2023-03-24 18:50 UTC, Kayke-Fujinaka requested changes

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/auth/auth.module.ts
> +import { RevokedToken } from './infra/typeorm/entities/revoked-token.entity';
Usa o Path Mapping do `@auth` na importação do RevokedToken e do RefreshToken

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/auth/auth.service.ts
> +  async validateUser({ email, password }: LoginDTO): Promise<User> {
Não tem sentido passar a password como parâmetro sendo que ela está sendo inutilizada.
É necessário verificar tanto se o email e a senha estão válidas.

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/auth/auth.service.ts
> +      throw new UnauthorizedException('Refresh token inválido');
As exceções viraram português a partir dessa exceção!

Seguir um padrão ou mudar tudo para português direto

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/auth/dto/login.dto.ts
> +    description: 'email do usuário',
Colocar o "email" iniciando como maiúsculo.

"Email do usuário"

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/auth/dto/refresh-token.dto.ts
> +  @ApiProperty({
Manter no padrão de deixar a @ApiProperty abaixo dos outros decorators

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/users/use-cases/findByEmail/findByEmail.ts
> +export class FindByEmail {
Muda o nome do ARQUIVO para find-by-email e já muda o do find-by-id, também.

Siga o padrão do register-user.ts e etc

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/users.e2e.spec.ts
> +  describe('Find user by id', () => {
Arrume os testes de integração de acordo com as novas mudanças de Auth

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/users.e2e.spec.ts
> +  describe('Find user by id', () => {
Isso é tanto para os do User quando da Transaction

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/users.controller.ts
> +  findById(@Query('id') id: string): Promise<User> {
Seria um params e não um query

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/auth.controller.ts
> +  @Post('logout')
"/logout"

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/auth.controller.ts
> +  async logout(@Request() req) {
Faltou tipar a request

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/auth.controller.ts
> +  @Post('refresh')
"/refresh"

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/shared/infra/http/controllers/auth.controller.ts
> +  @Post('login')
"/login"

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/auth/interfaces/IJwtPayload.ts
> +  iat?: number;
É assim mesmo o padrão do JWT.

O `iat` ou `issued at time` seria um created_at do token, ou seja, qual a hora que ele foi emitido.

Já o `exp` é o tempo de expiração.

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/auth/infra/typeorm/repositories/refresh-token.repository.ts
> +import * as crypto from 'node:crypto';
Importa o randomBytes direto do crypto

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/auth/guards/index.ts
> +export * from './local-auth.guard';
Faltou exportar o refresh token guards

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/auth/guards/refresh-token.guard.ts
> +    if (!isValid) {
Dar um enter da linha 22 para 23

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/auth/guards/refresh-token.guard.ts
> +    if (!refreshToken) {
Dar um enter da linha 17 para 18

2023-03-24 18:50 UTC, Kayke-Fujinaka commented on server/src/auth/guards/jwt-auth.guard.ts
> +    const isPublic = this.reflector.getAllAndOverride<boolean>(IS_PUBLIC_KEY, [
Crie um env example explicando sobre todos as variáveis de ambiente que estamos utilizando no projeto.

É só mandar para a GPT com todas as variáveis e peça para que ela crie um .env de exemplo.

2023-03-27 20:07 UTC, merged