feat/transactions-cooldownFeature
Grupo-GCB/academy-gamification pull request #44
Opened 2023-03-30 20:47 UTC by VitorMantovani

Nest PR implementei a feature de tempo de espera para o cadastro de uma transação.
Arrumei o logout do usuário.

2023-03-30 20:58 UTC, Kayke-Fujinaka requested changes

2023-03-30 20:58 UTC, Kayke-Fujinaka commented on server/src/transactions/dto/find-latest-transaction-by-status-and-subtype.ts
> +export class FindLatestTransactionByUserAndSubTypeDTO {
Muda o nome desse caso de uso como um todo, ou seja, todo o projeto que tiver esse nome gigante tu vai mudar inclusive o nome dos arquivos e pastas, também.

LatestTransactionByUserAndSubTypeDTO

2023-03-30 20:58 UTC, Kayke-Fujinaka commented on server/src/transactions/dto/find-latest-transaction-by-status-and-subtype.ts
> +  @IsNotEmpty()
Coloca uma mensagem dentro desse DTO:
  @IsNotEmpty({ message: 'Insira o e-mail do colaborador!' })

2023-03-30 20:58 UTC, Kayke-Fujinaka commented on server/src/transactions/dto/find-latest-transaction-by-status-and-subtype.ts
> +  @IsUUID()
@IsUUID(undefined, { message: 'Id inválido!' })

2023-03-30 20:58 UTC, Kayke-Fujinaka commented on server/src/transactions/dto/find-latest-transaction-by-status-and-subtype.ts
> +  @IsNotEmpty()
@IsNotEmpty({ message: 'Insira um subtipo!' })

2023-03-30 20:58 UTC, Kayke-Fujinaka commented on server/src/transactions/dto/find-latest-transaction-by-status-and-subtype.ts
> +  @IsEnum(CollaborationsSubType)
@IsEnum(TransactionSubType, {
    message:
      'O subtipo deve ser um dos seguintes valores: LOGIC_EXERCISE, CODE_REVIEW, COMMITTEE, DOUBTS, PAIR_PROGRAMMING, FEEDBACK, TEAM_CEREMONY!',
  })

2023-03-30 20:58 UTC, Kayke-Fujinaka commented on server/src/transactions/dto/find-latest-transaction-by-status-and-subtype.ts
> +import { IsNotEmpty, IsEnum, IsUUID } from 'class-validator';
Arrumar os imports deixando a importação de lib na linha 1 e as outras com um enter de distância

2023-03-30 20:58 UTC, Kayke-Fujinaka commented on server/src/transactions/test/in-memory/inMemoryTransactions.ts
> +    if (filteredTransactions.length === 0) {
Coloca o return na mesma linha e deixa esse 0 em uma variável falando que é o mínimo ou até mesmo um variável com toda essa condição falando o que ela é

2023-03-30 20:58 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/findLatestTransactionByUserAndSubType/find-Latest-Transaction-By-User-And-Sub-Type.ts
> +import { Injectable } from '@nestjs/common';
Arrumar os imports

2023-03-30 20:58 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/findLatestTransactionByUserAndSubType/find-latest-transaction-by-user-and-subtype.spec.ts
> +describe('FindLatestTransactionByUserAndSubType', () => {
Melhora esse nome seguindo o padrão dos outros!

2023-03-30 20:58 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/findLatestTransactionByUserAndSubType/find-latest-transaction-by-user-and-subtype.spec.ts
> +  it('should be able to find the latest transaction by user and subType', async () => {
subtype

2023-03-30 20:58 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/registerTransaction/register-transaction.ts
> +            `Tem de espera para cadastrar ${subType} ainda não terminou`,
"Tempo de espera para cadastrar..." e coloca exclamação no final

2023-03-30 20:58 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/registerTransaction/register-transaction.ts
> +    const userData = await this.usersRepository.findByEmail(data.user);
Tipa a variável

2023-03-30 20:58 UTC, Kayke-Fujinaka commented on server/src/transactions/use-cases/registerTransaction/register-transaction.ts
> +    const responsibleData = await this.usersRepository.findByEmail(
Tipa a variável

2023-03-31 02:15 UTC, GuWuelta approved these changes

2023-03-31 19:33 UTC, Kayke-Fujinaka requested changes

2023-03-31 19:33 UTC, Kayke-Fujinaka commented on server/src/auth/test/in-memory/InMemoryRefreshTokenRepository.ts
> +import { v4 as uuidv4 } from 'uuid';
Não estamos utilizando a lib uuid.

Utilize o node:crypto

2023-03-31 19:33 UTC, Kayke-Fujinaka commented on server/src/auth/use-cases/login/login.ts
> +import { IRefreshTokenRepository } from '@auth/interfaces';
Tem um outro import chamando o @auth/interfaces abaixo

2023-03-31 19:33 UTC, Kayke-Fujinaka commented on server/src/auth/use-cases/refresh/refresh.ts
> +import { IJwtPayload } from '@auth/interfaces';
Tira esse import e junta com o de cima

2023-03-31 19:33 UTC, Kayke-Fujinaka commented on server/src/auth/use-cases/refresh/refresh.ts
> +  async execute(token: string) {
Retorna o método

2023-03-31 19:33 UTC, Kayke-Fujinaka commented on server/src/auth/use-cases/validateUser/validate-user.spec.ts
> +describe('ValdiateUser', () => {
Describe tá errado!

"Validade User"

2023-03-31 19:33 UTC, Kayke-Fujinaka commented on server/src/auth/use-cases/validateUser/validate-user.spec.ts
> +    console.log(validatedUser);
Remove o log

2023-03-31 19:33 UTC, Kayke-Fujinaka commented on server/src/auth/use-cases/validateUser/validate-user.ts
> +    throw new Error('Endereço de e-mail ou senha incorretos');
Coloca exclamação no final!

2023-03-31 19:33 UTC, GuWuelta requested changes

2023-03-31 19:33 UTC, GuWuelta commented on server/src/auth/use-cases/refresh/refresh.spec.ts
> +      UnauthorizedException,
Bad Request Exception

2023-03-31 19:33 UTC, GuWuelta commented on server/src/auth/use-cases/refresh/refresh.ts
> +      throw new UnauthorizedException('Token de atualização inválido!');
Bad Request Exception

2023-03-31 19:33 UTC, GuWuelta commented on server/src/auth/use-cases/refresh/refresh.ts
> +      throw new UnauthorizedException('Token de atualização expirado!');
Bad Request Exception

2023-03-31 19:42 UTC, RafaRamosCosta requested changes

2023-03-31 19:42 UTC, RafaRamosCosta commented on server/src/auth/test/in-memory/InMemoryRefreshTokenRepository.ts
> +    refreshToken.expiresAt = new Date(Date.now() + expiresAt);
Usar um Object.assign()

2023-03-31 19:42 UTC, RafaRamosCosta commented on server/src/auth/use-cases/login/login.spec.ts
> +    expect(storedRefreshToken.user).toEqual(user.id);
colocar todos os expects no final do teste

2023-03-31 19:42 UTC, RafaRamosCosta commented on server/src/auth/use-cases/logout/logout.ts
> +    }
tirar o try catch

2023-03-31 19:42 UTC, RafaRamosCosta commented on server/src/auth/use-cases/validateUser/validate-user.spec.ts
> +    user.password = undefined;
modifica pra null

2023-03-31 19:42 UTC, RafaRamosCosta commented on server/src/auth/use-cases/validateUser/validate-user.ts
> +      if (isPasswordValid) return { ...user, password: undefined };
troca pra null

2023-03-31 19:54 UTC, Kayke-Fujinaka approved these changes

2023-03-31 19:56 UTC, Kayke-Fujinaka approved these changes

2023-03-31 19:59 UTC, GuWuelta requested changes

2023-03-31 19:59 UTC, GuWuelta commented on server/src/auth/use-cases/logout/logout.ts
> +      throw new BadRequestException('Token inválido!');
Remover esse try catch

2023-03-31 20:05 UTC, merged